### ISSUE TITLE
Secure frontend-backend communication with JWT in React

### ISSUE THREAD

**Issue by artur24814** [artur24814/ClearFrame#10]
Add middleware in React to automatically attach JWT tokens to every request to the backend.

- [x] Configure axios (or another method) to automatically add the JWT token to headers.
- [x] Implement token refresh logic.
- [x] Handle unauthorized requests and log out the user when the token expires.

**Comment by aadarsh10c** [comment]
hi @artur24814 , i would like to work on this issue

**Comment by artur24814** [comment]
Hi, @aadarsh10c, Ok, i gonna add you to project.
